AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Create S3 bucket For the web content.

Resources:
  S3BucketIndexFile:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "s3bucketindexfileappserver"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  S3BucketIndexFile:
    Description: Security Group ID for EC2 instances
    Value: !Ref S3BucketIndexFile
    Export:
      Name: S3BucketIndexFileId
