AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFormation template to create an Auto Scaling Group (ASG) with Launch Template, Scaling Policies, and integration with existing VPC and subnets.

Parameters:
#------------ Pre created Parametrs Network and Subnets ------------
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-066cd775db66747c2
    Description: VPC ID to deploy the ASG
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-0391d852ad9b5eb75,subnet-08644d84dd075fbdc
    Description: List of Private Subnet IDs
  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-086aaccd60fa3bc74,subnet-0f8ce19ad4facb2d0
    Description: List of PublicSubne Subnet IDs
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type
#------------ ASG Paramters ------------
  # AMIId:
  #   Type: String
  #   Description: AMI (Image) ID for the EC2 instances
  MaxInstances:
    Type: Number
    Default: 4
    Description: Maximum number of instances in the ASG
  MinInstances:
    Type: Number
    Default: 2
    Description: Minimum number of instances in the ASG
  DesiredInstances:
    Type: Number
    Default: 2
    Description: Desired number of instances in the ASG
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: PrivateEC2KeyPair
    Description: Key pair name for SSH access

#------------ ALB Paramters ------------
  ALBListenerPort:
    Type: Number
    Default: 80
    Description: ALB Listener Port Number
#------------ ScalingPolicy Paramter (PreDefined Scaling Metric Type) ------------
  PredefinedMetricType:
    Type: String
    Default: ASGAverageCPUUtilization  # Updated default value to a valid one
    Description: Choose the predefined metric for scaling (e.g., ASGAverageCPUUtilization, ALBRequestCountPerTarget)
    AllowedValues:
      - ASGAverageCPUUtilization
      - ALBRequestCountPerTarget
      - ASGAverageNetworkIn
      - ASGAverageNetworkOut
    # Parameter for Scaling Up Target Value
  TargetValueUp:
    Type: Number
    Default: 50
    Description: Target value for the chosen Scaling -UP- metric ! Make sure to enter the correct value accourding to the selected matric

  # Parameter for Scaling Down Target Value
  TargetValueDown:
    Type: Number
    Default: 30
    Description: Target value for the chosen Scaling -DOWN- metric ! Make sure to enter the correct value accourding to the selected matric

Resources:
 #------------ LaunchTemplate ------------
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: LaunchTemplate_Dev
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        ImageId: ami-02df5cb5ad97983ba #Amazon Linux 
        NetworkInterfaces:
          - AssociatePublicIpAddress: false
            SubnetId: !Select [0, !Ref PrivateSubnetIds]
            DeviceIndex: 0  
        Monitoring:
          Enabled: true
        BlockDeviceMappings:
          - DeviceName: /dev/xvda  # Root volume
            Ebs:
              VolumeType: gp3
              VolumeSize: 20
              Encrypted: true
              DeleteOnTermination: true
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: ASGPrivateInstance_DEV
        UserData:
          Fn::Base64: 
            !Sub |
              #!/bin/bash
              # Update system
              yum update -y

              # Install dependencies
              yum install -y httpd awscli

              # Configure additional EBS volume
              DEVICE="/dev/xvdf"
              MOUNT_POINT="/mnt/data"

              # Check if the device exists
              if [ -b $DEVICE ]; then
                # Create filesystem if not already created
                if ! blkid $DEVICE; then
                  mkfs -t ext4 $DEVICE
                fi

                # Create mount point
                mkdir -p $MOUNT_POINT

                # Add to fstab
                echo "$DEVICE $MOUNT_POINT ext4 defaults,nofail 0 2" >> /etc/fstab

                # Mount the volume
                mount -a
              fi

              # Start and enable web server
              systemctl start httpd
              systemctl enable httpd
              # Get the EC2 instance ID from metadata
              INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
              # Create sample index page
              echo "<h1>Hello from Tweet App ServerDEV</h1>" > /var/www/html/index.html
              echo "<p>Additional data volume mounted at $MOUNT_POINT</p>" >> /var/www/html/index.html

# ------------ AutoScalingGroup ------------
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn:
      - LaunchTemplate
    Properties:
      AutoScalingGroupName: AutoScalingGroupForDevVPC
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier: !Ref PrivateSubnetIds
      MinSize: !Ref MinInstances
      MaxSize: !Ref MaxInstances
      DesiredCapacity: !Ref DesiredInstances
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: ASGInstance
          PropagateAtLaunch: true
  # #------------ Scaling Policy ------------
  ScalingPolicyUp:
    Type: AWS::AutoScaling::ScalingPolicy
    DependsOn:
      - AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: !Ref PredefinedMetricType
        TargetValue: !Ref TargetValueUp

  ScalingPolicyDown:
    Type: AWS::AutoScaling::ScalingPolicy
    DependsOn:
      - AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: !Ref PredefinedMetricType
        TargetValue: !Ref TargetValueDown
  # #------------  Application Load Balancer (ALB) ------------
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: TweetALBDEV
      Scheme: internet-facing
      Subnets: !Ref PrivateSubnetIds
      Tags:
        - Key: Name
          Value: TweetALBDev

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TweetALBTargetGroup
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckEnabled: true
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: !Ref ALBListenerPort
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
    DependsOn:
      - ApplicationLoadBalancer
      - ALBTargetGroup
      
Outputs:
  AutoScalingGroupName:
    Description: The name of the Auto Scaling Group
    Value: !Ref AutoScalingGroup
  LaunchTemplateId:
    Description: The ID of the Launch Template created for the ASG
    Value: !Ref LaunchTemplate
