version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_app
      - DB_PORT=5432
      - JWT_SECRET=7c3d9f82a1e5b409f6e7c8d2a4b0c9d3e5f7a1b2c8d9e0f3a4b5c6d7e8f9a0b
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persist pgAdmin data
    depends_on:
      - db


volumes:
  postgres_data:
  pgadmin_data: